import colors from "../constants/colors";

const styles = {
  // ── App shell ──────────────────────────────────────────
  app: {
    minHeight: "100vh",
    background: colors.cream,
    fontFamily: "'Inter', sans-serif",
    color: colors.ink,
    display: "flex",
    flexDirection: "column",
    paddingBottom: 80,
  },
  loadingScreen: {
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    background: colors.cream,
  },
  loadingPill: {
    width: 56,
    height: 56,
    borderRadius: "50%",
    background: colors.sageLight,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },

  // ── Header ─────────────────────────────────────────────
  header: {
    background: colors.cream,
    borderBottom: `1px solid ${colors.line}`,
    position: "sticky",
    top: 0,
    zIndex: 10,
  },
  headerInner: {
    maxWidth: 480,
    margin: "0 auto",
    padding: "16px 20px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  brand: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  brandMark: {
    width: 38,
    height: 38,
    borderRadius: 12,
    background: colors.sage,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  brandTitle: {
    fontFamily: "'Fraunces', serif",
    fontSize: 19,
    fontWeight: 600,
    lineHeight: 1.1,
  },
  brandSubtitle: {
    fontSize: 12,
    color: colors.inkSoft,
    textTransform: "capitalize",
  },
  notifButton: (active) => ({
    display: "flex",
    alignItems: "center",
    gap: 6,
    border: `1px solid ${colors.sage}`,
    borderRadius: 20,
    padding: "6px 12px",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: 13,
    background: active ? colors.sage : "transparent",
    color: active ? colors.cream : colors.sageDark,
  }),

  // ── Main ───────────────────────────────────────────────
  main: {
    flex: 1,
    maxWidth: 480,
    width: "100%",
    margin: "0 auto",
    padding: "20px",
    boxSizing: "border-box",
  },

  // ── Nav ────────────────────────────────────────────────
  nav: {
    position: "fixed",
    bottom: 0,
    left: 0,
    right: 0,
    background: "#fff",
    borderTop: `1px solid ${colors.line}`,
    display: "flex",
    justifyContent: "center",
    gap: 40,
    padding: "10px 0 14px",
  },
  navButton: (active) => ({
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
    background: "transparent",
    border: "none",
    cursor: "pointer",
    fontFamily: "inherit",
    color: active ? colors.sageDark : colors.inkSoft,
  }),
  navIconWrap: (active) => ({
    width: 40,
    height: 32,
    borderRadius: 12,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: active ? colors.sageLight : "transparent",
  }),

  // ── Today view ─────────────────────────────────────────
  progressCard: {
    background: "#fff",
    borderRadius: 18,
    padding: 20,
    border: `1px solid ${colors.line}`,
  },
  progressLabel: {
    fontSize: 13,
    color: colors.inkSoft,
    marginBottom: 4,
  },
  progressNumbers: {
    fontFamily: "'Fraunces', serif",
    fontSize: 36,
    fontWeight: 600,
    color: colors.sageDark,
  },
  progressRing: (pct) => ({
    width: 56,
    height: 56,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: `conic-gradient(${colors.sage} ${pct * 3.6}deg, ${colors.sageLight} 0deg)`,
  }),
  notifBanner: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    marginTop: 12,
    background: colors.sageLight,
    color: colors.sageDark,
    border: "none",
    borderRadius: 12,
    padding: "10px 14px",
    fontSize: 13,
    cursor: "pointer",
    fontFamily: "inherit",
    textAlign: "left",
    boxSizing: "border-box",
  },
  notifBannerDenied: {
    marginTop: 12,
    background: colors.coralLight,
    color: colors.coral,
    borderRadius: 12,
    padding: "10px 14px",
    fontSize: 13,
  },
  doseRow: (taken) => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    background: "#fff",
    borderRadius: 14,
    padding: "14px 16px",
    border: `1px solid ${colors.line}`,
    marginBottom: 10,
    opacity: taken ? 0.6 : 1,
    transition: "opacity 0.2s",
  }),
  doseDot: (color) => ({
    width: 10,
    height: 10,
    borderRadius: "50%",
    flexShrink: 0,
    background: color,
  }),
  doseTime: {
    fontSize: 12,
    color: colors.inkSoft,
    fontWeight: 600,
    letterSpacing: 0.5,
  },
  doseName: {
    fontFamily: "'Fraunces', serif",
    fontSize: 17,
    fontWeight: 600,
    marginTop: 2,
  },
  doseDosage: {
    fontSize: 13,
    color: colors.inkSoft,
  },
  checkButton: (taken) => ({
    width: 40,
    height: 40,
    borderRadius: "50%",
    border: `2px solid ${taken ? colors.sage : colors.line}`,
    background: taken ? colors.sage : "transparent",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    flexShrink: 0,
    transition: "all 0.15s",
  }),

  // ── Meds view ──────────────────────────────────────────
  sectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  sectionTitle: {
    fontFamily: "'Fraunces', serif",
    fontSize: 24,
    fontWeight: 600,
    margin: 0,
  },
  addButton: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: colors.sage,
    color: colors.cream,
    border: "none",
    borderRadius: 20,
    padding: "8px 16px",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  medCard: {
    background: "#fff",
    borderRadius: 16,
    padding: 16,
    border: `1px solid ${colors.line}`,
    marginBottom: 12,
  },
  medCardInner: {
    display: "flex",
    gap: 12,
  },
  medColorBar: (color) => ({
    width: 4,
    borderRadius: 4,
    alignSelf: "stretch",
    background: color,
  }),
  medCardContent: {
    flex: 1,
  },
  medCardRow: {
    display: "flex",
    justifyContent: "space-between",
  },
  medName: {
    fontFamily: "'Fraunces', serif",
    fontSize: 18,
    fontWeight: 600,
  },
  medDosage: {
    fontSize: 13,
    color: colors.inkSoft,
  },
  medActions: {
    display: "flex",
    gap: 8,
  },
  medTimes: {
    display: "flex",
    gap: 6,
    flexWrap: "wrap",
    marginTop: 10,
  },
  timeTag: {
    background: colors.sageLight,
    color: colors.sageDark,
    fontSize: 12,
    fontWeight: 600,
    borderRadius: 8,
    padding: "3px 8px",
  },
  medMeta: {
    fontSize: 12,
    color: colors.inkSoft,
    marginTop: 8,
  },
  medNotes: {
    fontSize: 13,
    color: colors.ink,
    marginTop: 8,
    fontStyle: "italic",
    background: colors.cream,
    borderRadius: 8,
    padding: "8px 10px",
  },

  // ── Shared ─────────────────────────────────────────────
  iconButton: {
    background: "transparent",
    border: "none",
    cursor: "pointer",
    padding: 6,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  emptyState: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    padding: "48px 20px",
    background: "#fff",
    borderRadius: 16,
    border: `1px solid ${colors.line}`,
  },
  emptyTitle: {
    fontFamily: "'Fraunces', serif",
    fontSize: 18,
    fontWeight: 600,
    marginTop: 12,
  },
  emptyText: {
    fontSize: 13,
    color: colors.inkSoft,
    marginTop: 6,
    maxWidth: 260,
  },

  // ── Modal ──────────────────────────────────────────────
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(58,53,48,0.4)",
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    zIndex: 100,
  },
  modal: {
    background: colors.cream,
    borderRadius: "20px 20px 0 0",
    width: "100%",
    maxWidth: 480,
    maxHeight: "90vh",
    overflowY: "auto",
    padding: 24,
    boxSizing: "border-box",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  modalTitle: {
    fontFamily: "'Fraunces', serif",
    fontSize: 20,
    fontWeight: 600,
    margin: 0,
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  label: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    fontSize: 13,
    fontWeight: 600,
    color: colors.sageDark,
  },
  input: {
    fontFamily: "inherit",
    fontSize: 15,
    padding: "10px 12px",
    borderRadius: 10,
    border: `1px solid ${colors.line}`,
    background: "#fff",
    color: colors.ink,
    outline: "none",
  },
  inputRow: {
    display: "flex",
    gap: 8,
    marginTop: 6,
  },
  addTimeButton: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    marginTop: 8,
    background: "transparent",
    border: `1px dashed ${colors.sage}`,
    borderRadius: 10,
    padding: "8px 12px",
    color: colors.sageDark,
    fontSize: 13,
    cursor: "pointer",
    fontFamily: "inherit",
    width: "fit-content",
  },
  submitButton: {
    background: colors.sage,
    color: colors.cream,
    border: "none",
    borderRadius: 12,
    padding: "14px",
    fontSize: 15,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "inherit",
    marginTop: 8,
  },

  // ── History view ───────────────────────────────────────
  calendarCard: {
    background: "#fff",
    borderRadius: 16,
    padding: 16,
    border: `1px solid ${colors.line}`,
  },
  calendarHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  calendarMonth: {
    fontFamily: "'Fraunces', serif",
    fontSize: 17,
    fontWeight: 600,
    textTransform: "capitalize",
  },
  calendarGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    gap: 6,
  },
  calendarWeekday: {
    textAlign: "center",
    fontSize: 11,
    color: colors.inkSoft,
    fontWeight: 600,
    paddingBottom: 4,
  },
  calendarCell: (bg, textColor, isToday) => ({
    aspectRatio: "1",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    fontSize: 13,
    fontWeight: 500,
    background: bg,
    color: textColor,
    border: isToday ? `2px solid #4F6B58` : "2px solid transparent",
  }),
  legend: {
    display: "flex",
    gap: 16,
    justifyContent: "center",
    marginTop: 16,
  },
  legendDot: (color) => ({
    width: 12,
    height: 12,
    borderRadius: 4,
    background: color,
  }),
};

export default styles;
